# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75604d0b7156a3ca735418e79a34dcf51e4d4b649be1600b32488557232d8d99d7bb6a2aa37ae8d6c88ba4fe7f87588aae4cc13d4bee564adf0ac03858bc5652

test:
  secret_key_base: d8131eaf24403a9ba634f739a17cc80e117989591385ebc47f034f84d3112e8121748bb16d34db53ea4625e1f24cffe429151b885441b327f1403cc0d6f775d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
